### ISSUE TITLE
feature request: sqrt 

### ISSUE THREAD

**Issue by fxfactorial** [holiman/uint256#100]
thank you

**Comment by holiman** [comment]
Yup, I guess it fis. 
The `big.Int` algo looks pretty tidy: https://github.com/golang/go/blob/master/src/math/big/nat.go#L1213

**Comment by fxfactorial** [comment]
Perfect thank you

**Comment by holiman** [comment]
Wait what? Why did you close it.  

I meant that the feature request was a good feature request, and that if we want to add it, we could easily use the implementation from big.Int.

**Comment by fxfactorial** [comment]
ah, I thought you meant like "go implement yourself" , my bad 

sure, my team will try to upstream the impl
