### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by lmittmann** [holiman/uint256#116]
hi @holiman, could you make a new tag / release? There are so many improvements / additions since the last tag.

**Comment by holiman** [comment]
I've kind of been waiting for https://github.com/google/oss-fuzz/pull/6497 to get merged, but it'll have it's first anniversary soon so maybe it's not worth waiting for... :cry:

**Comment by lmittmann** [comment]
...maybe just make another tag if that PR is merged?!

**Comment by damiensgit** [comment]
> I've kind of been waiting for [google/oss-fuzz#6497](https://github.com/google/oss-fuzz/pull/6497) to get merged, but it'll have it's first anniversary soon so maybe it's not worth waiting for... 😢

Your PR has been accepted - wen release :)

**Comment by holiman** [comment]
It hasn't had any actual time on the tarmac yet, because the build was failing. Hopefully works now (https://github.com/google/oss-fuzz/pull/8370), and once it's had some actual runtime, it's time for a new release.

**Comment by holiman** [comment]
https://github.com/holiman/uint256/releases/tag/v1.2.1
