### ISSUE TITLE
Implement `Dec()` and `PrettyDec()` properly

### ISSUE THREAD

**Issue by karalabe** [holiman/uint256#129]
When printing ints in logs or console, it's usually better to print as a decimal vs hex. But there's no way to flatten a uint256 Int currently into a decimal string. It feels a bit wonky to do `uint256.Int.ToBig().String()`

**Comment by holiman** [comment]
There should be two methods: 

- One that prints to decimal: e.g `123012313` (see `Dec` below)
- One that pretty-prints with thousands-separators: `123,012,313` (`PrettyDec`?) 

ps, `Dec` exists and currently looks like this: 

```golang
func (z *Int) Dec() string {
	return z.ToBig().String()
}
```

**Comment by karalabe** [comment]
Ah, sry, when I backported the log change from my PR I didn't backport bumping the uint256 lib version.

**Comment by holiman** [comment]
I'll reopen this, we should still implement it "properly" without going via big

**Comment by holiman** [comment]
Fixed by https://github.com/holiman/uint256/pull/130
