### ISSUE TITLE
Unexpected overflows

### ISSUE THREAD

**Issue by dthuering** [holiman/uint256#147]
We are getting overflow errors in go-ethereum from the `uint256.FromBig` method.

```go
R, ok = uint256.FromBig((*big.Int)(dec.R))
```

Here are the logs with the values that cause the overflow error (`dec.R.String()`).

```
INFO   [0007] (tx-listener.session.ethereum.hook): block processed  block_number=5263607 chain=4b0aed40-c2da-44b1-9396-50233910590e owner_id= tenant_id=_
'r' value overflows uint256: 0xb75685b724028d4cc66bd8ff0aa46b6e4721842ac1f7f4880563b581dcfb2ee
's' value overflows uint256: 0x4cdd5a8417fa2c49aa472b8e079e01f276120089ea0c7b27df4533193876abed
'v' value overflows uint256: 0x1
'r' value overflows uint256: 0x241bff69a5506e1a26543b97b22854ec556f822b71627a3136f245e05b98fda9
's' value overflows uint256: 0x7a8ee9210af64eee6e3a15b331ea7d491d3d983f93d52b06f97282a050a9e973
'v' value overflows uint256: 0x1
```

That does not seem right. What is going wrong here?

Thanks for cheking!

**Comment by holiman** [comment]
Could you please also attach the code which prints out the error? So I see both the code producing an error and printing it, thanks

**Comment by dthuering** [comment]
Here is the code with my changes for logging from the go-ethereum library.

```go
		itx.R, ok = uint256.FromBig((*big.Int)(dec.R))
		if !ok {
			fmt.Printf("'r' value overflows uint256: %s\n", dec.R.String())
			//return errors.New("'r' value overflows uint256")
		}
```

Here the original code.
https://github.com/ethereum/go-ethereum/blob/v1.12.2/core/types/transaction_marshalling.go#L380

It also happens in the newest v1.13.12 version. I am just on the older one as we use it in [Orchestrate](https://github.com/Consensys/orchestrate) and don't want to update to latest yet but need to support newest changes on Sepolia.

Thank you!

**Comment by holiman** [comment]
Original code looks bad. It's not "ok" , it's "overflow" iirc.

**Comment by holiman** [comment]
Nice. So this can be closed, right?

**Comment by dthuering** [comment]
Unfortunately not, the error still overflow happens in the newer version. Just the variable was renamed to `overflow`.

Could it be, that it is indeed overflowing but would fit into a `uint256` as mentioned in the _go-ethereum_ issue?

**Comment by namiloh** [comment]
You are reading it wrong. `overflow = !ok`. You have negated the boolean

**Comment by holiman** [comment]
Instead of 
```golang
		itx.R, ok = uint256.FromBig((*big.Int)(dec.R))
		if !ok {
			fmt.Printf("'r' value overflows uint256: %s\n", dec.R.String())
			//return errors.New("'r' value overflows uint256")
		}
```
You should do 
```golang
		itx.R, overflow = uint256.FromBig((*big.Int)(dec.R))
		if overflow {
			fmt.Printf("'r' value overflows uint256: %s\n", dec.R.String())
			//return errors.New("'r' value overflows uint256")
		}
```
Note: `!ok` is changed to `overflow`.
