### ISSUE TITLE
Publish with permissive license

### ISSUE THREAD

**Issue by Kubuxu** [holiman/uint256#17]
Hi, I would like to ask if it would be possible to license this code under a more permissive license. GPL is viral and LGPL is hard to apply to Golang as there are no shared libraries.

MIT or Apache-2 would work best the projects I would like to use it for (libp2p/ipfs).

I fully understand any objections against it.

**Comment by holiman** [comment]
Sure, I can switch it to MIT

**Comment by karalabe** [comment]
BSD-3?

**Comment by holiman** [comment]
Would that work @Kubuxu  ?

**Comment by Kubuxu** [comment]
Yes, it works for me. Thanks!
