### ISSUE TITLE
[ Bug ] Bytes32 does not marshal Int into little-endian byte array

### ISSUE THREAD

**Issue by renaynay** [holiman/uint256#22]
When calling `Bytes32()` on an Int `[4]uint64{uint64(0), uint64(0), uint64(0), uint64(1)}` (according to directions here https://github.com/holiman/uint256/blob/master/uint256.go#L40 where Int[3] is most significant), I get the following bytes: 

`[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]`

**There are a few issues with the above:** 
* If `Int[3]` is most significant and `Int[0]` is least significant as per https://github.com/holiman/uint256/blob/master/uint256.go#L40, then that would be big-endian order rather than little-endian as described
* the marshaling of the input is neither in big or little-endian order

If I call `Bytes32()` on an Int `[4]uint64{uint64(1), uint64(0), uint64(0), uint64(0)}` (where the input is in little-endian order, with most significant at `Int[0]`), I get the following output: 

`[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]`

The output above is in big-endian order which contradicts the description here: https://github.com/holiman/uint256/blob/master/uint256.go#L99

**Expected behavior:** 

Input of `[4]uint64{uint64(1), uint64(0), uint64(0), uint64(0)}` marshals to `[]byte{1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}` when `Bytes32()` is called on Input.

**Comment by holiman** [comment]
I remember working on this a few weeks ago, thought it was fixed. I will look into it next week. Thanks!!

**Comment by holiman** [comment]
First of all, the "golden source of truth" for how this library _should_ behave, is that it should behave the same way as `big.Int`. 
For `big.Int.Bytes()`, the docs say
```
// Bytes returns the absolute value of x as a big-endian byte slice.
```
So therefore, you are right that the docs are wrong, and should say `Byte32 returns a the a 32 byte big-endian array.`

I added the following test: 
```
func TestConversion(t *testing.T) {
	a := big.NewInt(1)
	b, _ := NewFromBig(a)
	if exp, got := a.Bytes(), b.Bytes(); !bytes.Equal(got, exp) {
		t.Fatalf("got %x exp %x", got, exp)
	}
	fmt.Printf("big.Int:     %x\n", a.Bytes())
	fmt.Printf("uint256.Int: %x\n", b.Bytes())
	a = big.NewInt(0x1000000000000000)
	b, _ = NewFromBig(a)
	if exp, got := a.Bytes(), b.Bytes(); !bytes.Equal(got, exp) {
		t.Fatalf("got %x exp %x", got, exp)
	}
	fmt.Printf("big.Int:     %x\n", a.Bytes())
	fmt.Printf("uint256.Int: %x\n", b.Bytes())
}
```
Which outputs
```
big.Int:     01
uint256.Int: 01
big.Int:     1000000000000000
uint256.Int: 1000000000000000
```
For `Bytes32`, I the "golden image" is the go-ethereum conversion from `big.Int` to `common.Hash` at https://github.com/holiman/go-ethereum/blob/master/common/types.go#L51 , and for `Bytes20` the corresponding source of truth is conversion to `common.Address`. 

I've added a test  to ensure that they are aligned. 

I often mix up the definitions, 

>  A big-endian ordering places the most significant byte first

Whenever I think about which is which, it _sounds_ to me like big-endian should mean biggest-at-the-end, which is wrong. So there may be other cases where I've used the wrong notation. Thanks for the report!

**Comment by holiman** [comment]
Oh, 

> If Int[3] is most significant and Int[0] is least significant as per https://github.com/holiman/uint256/blob/master/uint256.go#L40, then that would be big-endian order rather than little-endian as described


The internal ordering of the `uint64` that make up the `uint256` are not encompassed by big-endiannnes or little-endianness -- that refers to byte ordering. The internal representation of four `uint64` are as specified ( ` Int[3] is most significant and Int[0] is least significant`) -- which, I guess, is little-endian:ish. I consider it an internal detail, and it could be subject to change. For example, the library could be ported to 32-bit architecture using `uint32`s instead.
