### ISSUE TITLE
Create DIV based on Knuth Algorithm D

### ISSUE THREAD

**Issue by holiman** [holiman/uint256#5]
## Task

Implement integer division based on Knuth's algorithm D. The algo is described in the book "Hackers Delight", and is implemented in a lot of places over the internet. 
The golang int lib uses it internally, with `asm` backing. 

One implementation: https://deamentiaemundi.wordpress.com/2014/10/01/multiprecision-long-division-knuths-algorithm-d/ 
64/32 bit: http://www.hackersdelight.org/hdcodetxt/divmnu64.c.txt 
Golang impl: https://golang.org/src/math/big/nat.go#L611 

The task requires 

* Implementing it in pure go (no `asm`)
* The implementation must work on both big-endian and little-endian systems

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd9d70fce2a12018e235296021eb428f9093cfaea85204625d55d81a6859ca4c9](https://etherscan.io/tx/0xd9d70fce2a12018e235296021eb428f9093cfaea85204625d55d81a6859ca4c9)

**Comment by chfast** [comment]
I can implement this if not urgent.

**Comment by holiman** [comment]
Yes please @chfast!!
