### ISSUE TITLE
RLP decoding woes

### ISSUE THREAD

**Issue by holiman** [holiman/uint256#77]
We now have rlp encoding, and can encode RLP. However, RLP decoding requires to implement this interface: https://github.com/ethereum/go-ethereum/blob/44b41641f8220fe79e43461356c147cc3cc72380/rlp/decode.go#L64 

I.e, 
```
type Decoder interface {
	DecodeRLP(*Stream) error
}
```
Where `*Stream` is [this](https://github.com/ethereum/go-ethereum/blob/44b41641f8220fe79e43461356c147cc3cc72380/rlp/decode.go#L547) struct from the same package. 

If we want `uint256.Int` to implement that, it would require adding `rlp` as a dependency :( . 

@fjl any ideas to get us out of this? Seems quirky, from API-perspective, to have `Encoder` interface be implementable without rlp-dependency, but have the `Decoder` interface depend on package `rlp`.

**Comment by fjl** [comment]
The Decoder taking stream is an unfortunate design decision, but it does make the decoder work a bit faster because you have direct access to the underlying parser state in your custom decoder.

**Comment by holiman** [comment]
Yeah.. I'm thinking that maybe we'll add `DecodeRLPBytes([]byte) error`, and then the a 'custom' decoder can just do `a.DecodeRLPBytes(stream.Bytes())`.

**Comment by holiman** [comment]
I was thinking something like this: 
```golang
func (z *Int) DecodeRLPBytes(b []byte) error {
	// Check length
	if len(b) > 32 {
		return errors.New("rlp: uint overflow")
	}
	if len(b) == 0 {
		z.Clear()
		return nil
	}
	// Check leading zero-bytes
	if b[0] == 0 {
		return errors.New("rlp: non-canonical integer format")
	}
	z.SetBytes(b)
}
```
But I don't know -- perhaps not worth it, since we will have to have a custom `uint256`-decoder inside `rlp` anyway.

**Comment by fjl** [comment]
I think we can agree to just add special support for uint256 in package rlp.
