### ISSUE TITLE
The 1.2.0 release is not API compatible with 1.1.1, breaking SemVer assumptions

### ISSUE THREAD

**Issue by sztanpet** [holiman/uint256#84]
The 1.2.0 release broke the API, and thus should have been 2.0.0
The breaking change came in https://github.com/holiman/uint256/commit/b323bdcae551374e5fd126f9ba09729127759788
Where NewInt() changed to NewInt(val uint64).

This breaks [MVS](https://golang.org/ref/mod#minimal-version-selection), and thus all libraries depending on your library, like go-ethereum where currently new developers importing go-ethereum will get the latest compatible version of uint256 (the latest in version 1 which is 1.2.0) but is not actually compatible.
The result is new developers not being able to build their projects.

The steps to rectify this is:
- retract version 1.2.0 so that MVS no longer selects it, see: https://golang.org/ref/mod#go-mod-file-retract
- tag a new 2.0.0 version

**Comment by holiman** [comment]
Apologies for the inconvenience, but it's moot at this point to change. `uint256` is primarily built for go-ethereum, and I'm not going to retroactively fix this. Updating major version number is simply too cumbersome for such a tiny change -- but yes, in hindsight I agree it would have been the right thing to do.
